name: NodeJS with Webpack

# Define quando o robô deve trabalhar
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Rodar em várias versões garante que seu código é compatível
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 1. Baixa o seu código para dentro do servidor do GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instala a versão correta do Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Isso faz o processo ficar mais rápido nas próximas vezes

      # 3. Instala as dependências e roda o Webpack
      - name: Install and Build
        run: |
          npm ci
          npm run build